# pk232py - Modern multimode terminal for AEA PK-232 / PK-232MBX TNC
# Copyright (C) 2026  OE3GAS  -  GPL v2
"""P80: every Host Mode mnemonic the application sends is in the registry.

CLAUDE.md rule 6 ("never guess a mnemonic") made checkable: the scan finds each
mnemonic the source sends (tools/gen_mnemonic_audit.py), the registry
(comm/mnemonic_registry.py) must know it, and docs/MNEMONIC_AUDIT.md must be the
current rendering of the registry. A new mnemonic without an entry fails here.
"""

from __future__ import annotations

import sys
from pathlib import Path

import pytest

from pk232py.comm.mnemonic_registry import RELEASES, REGISTRY

_TOOLS = Path(__file__).resolve().parents[3] / "tools"
if str(_TOOLS) not in sys.path:
    sys.path.insert(0, str(_TOOLS))

import gen_mnemonic_audit as audit  # noqa: E402


class TestScanAgainstRegistry:
    def test_every_mnemonic_the_app_sends_is_registered(self):
        missing = {mn: sites[0][:2] for mn, sites in audit.scan_sources().items()
                   if mn not in REGISTRY}
        assert not missing, (
            "Host mnemonics without a comm/mnemonic_registry.py entry (add one, "
            f"with evidence or evidence={{}}): {missing}")

    def test_a_new_unregistered_mnemonic_makes_the_check_fail(self, tmp_path):
        """The scan sees a literal in a call, a table and a channel command -
        and the registry check would reject all of them."""
        pkg = tmp_path / "pk232py"
        (pkg / "modes").mkdir(parents=True)
        (pkg / "modes" / "fake.py").write_text(
            "from pk232py.comm.frame import build_command\n"
            "def a(): return build_command(b'ZZ')\n"
            "def b(sm): sm.send_channel_command(1, b'ZY')\n"
            "toggle_map = [(None, b'ZX')]\n"
            "# build_command(b'ZW') in a comment is NOT a call\n",
            encoding="utf-8")
        found = audit.scan_sources(pkg)
        unregistered = {mn for mn in found if mn not in REGISTRY}
        assert unregistered == {b"ZZ", b"ZY", b"ZX"}

    def test_tests_directory_is_not_scanned(self, tmp_path):
        pkg = tmp_path / "pk232py"
        (pkg / "tests").mkdir(parents=True)
        (pkg / "tests" / "t.py").write_text(
            "build_command(b'ZV')\n", encoding="utf-8")
        assert b"ZV" not in audit.scan_sources(pkg)

    def test_the_registry_holds_nothing_the_app_does_not_send(self):
        sent = set(audit.scan_sources())
        assert set(REGISTRY) <= sent, sorted(set(REGISTRY) - sent)


class TestRegistryShape:
    def test_entries_are_well_formed(self):
        for mn, entry in REGISTRY.items():
            assert entry.mnemonic == mn and len(mn) == 2
            assert entry.kind in {"mode", "param", "query", "action", "channel"}, mn
            assert entry.meaning, mn
            assert set(entry.evidence) <= set(RELEASES), mn

    def test_evidence_of_host_params_is_taken_over_not_retyped(self):
        from pk232py.comm.host_params import param_by_name
        for name in ("MAXFRAME", "UBIT", "MBELL"):
            row = param_by_name(name)
            assert set(REGISTRY[row.mnemonic].evidence) >= set(row.verified_releases), name

    def test_transmitting_entries_are_marked(self):
        assert REGISTRY[b"XM"].transmits and REGISTRY[b"CO"].transmits
        assert not REGISTRY[b"PA"].transmits


class TestAuditFile:
    def test_docs_mnemonic_audit_is_the_current_rendering(self):
        current = audit.AUDIT_FILE.read_text(encoding="utf-8").replace("\r\n", "\n")
        assert current == audit.render_audit(), (
            "docs/MNEMONIC_AUDIT.md is stale - run: "
            "python tools/gen_mnemonic_audit.py --update")

    def test_header_says_generated(self):
        first = audit.AUDIT_FILE.read_text(encoding="utf-8").splitlines()[0]
        assert "generated by test_mnemonic_registry" in first and "do not edit" in first
