# pk232py - Modern multimode terminal for AEA PK-232 / PK-232MBX TNC
# Copyright (C) 2026  OE3GAS  -  GPL v2
"""P90 - tools/build_scan_kit.py: a ZIP with a stand-alone scanner for other radio amateurs.

The generated scanner has what it needs from PK232PY copied in at build time (the wake-up byte, the banner
markers, escape_converse(), verbose_line(), the command matrix reader and the matrix itself as a table). The
test builds the kit and runs the embedded scanner in an EMPTY interpreter (-S -E: no site-packages, so no
pk232py and no .pth of the venv; only the standard library) in --selftest mode.

tools/ is not a package - see test_hw_check.py."""

from __future__ import annotations

import re
import subprocess
import sys
import zipfile
from pathlib import Path

import pytest

_TOOLS = Path(__file__).resolve().parents[3] / "tools"
if str(_TOOLS) not in sys.path:
    sys.path.insert(0, str(_TOOLS))

import build_scan_kit as kit  # noqa: E402

DATE = "2026-10-08"
FILES = {"pk232_fw_scan.py", "requirements.txt", "README_DE.md", "README_EN.md",
         "run_scan.bat", "run_scan.sh", "device_info.txt"}


@pytest.fixture
def built(tmp_path):
    zpath = kit.build_kit(tmp_path / "dist", date=DATE)
    out = tmp_path / "kit"
    with zipfile.ZipFile(zpath) as z:
        z.extractall(out)
    return zpath, out


class TestKitContents:

    def test_the_zip_is_named_by_the_date_and_holds_the_seven_files(self, built):
        zpath, out = built
        assert zpath.name == f"pk232_scan_kit_{DATE}.zip"
        with zipfile.ZipFile(zpath) as z:
            assert set(z.namelist()) == FILES

    def test_the_requirements_are_only_pyserial(self, built):
        _zpath, out = built
        lines = [ln.strip() for ln in (out / "requirements.txt").read_text().splitlines() if ln.strip()]
        assert len(lines) == 1 and lines[0].lower().startswith("pyserial")

    def test_building_twice_gives_the_same_bytes(self, tmp_path):
        a = kit.build_kit(tmp_path / "a", date=DATE).read_bytes()
        b = kit.build_kit(tmp_path / "b", date=DATE).read_bytes()
        assert a == b

    def test_the_scanner_is_marked_generated_and_a_kit(self, built):
        _zpath, out = built
        src = (out / "pk232_fw_scan.py").read_text(encoding="utf-8")
        assert "generated by build_scan_kit, do not edit" in src.splitlines()[2] + src.splitlines()[3]
        assert "\n_KIT = True\n" in src and "\n_KIT = False\n" not in src

    def test_the_scanner_needs_nothing_from_pk232py(self, built):
        _zpath, out = built
        src = (out / "pk232_fw_scan.py").read_text(encoding="utf-8")
        assert not re.search(r"^\s*(from|import)\s+pk232py", src, re.M)
        assert "sys.path.insert" not in src and "# >>> pk232py imports" not in src

    def test_the_matrix_is_embedded_as_a_table(self, built):
        _zpath, out = built
        src = (out / "pk232_fw_scan.py").read_text(encoding="utf-8")
        repo_csv = (Path(kit.REPO) / "src" / "pk232py" / "data" / "command_matrix.csv").read_text(encoding="utf-8")
        assert "_MATRIX_CSV" in src
        ns: dict = {}
        exec(compile(kit.embedded_matrix_text(src), "embedded", "exec"), ns)
        assert ns["_MATRIX_CSV"] == repo_csv.replace("\r\n", "\n")


class TestTheScannerRunsWithoutTheRepo:
    """Justification for the runtime: starts a second interpreter (~0.5 s), which IS the test - the scanner
    must run there with the standard library alone."""

    @staticmethod
    def _run(out, *args):
        return subprocess.run(
            [sys.executable, "-S", "-E", "pk232_fw_scan.py", *args], cwd=out,
            capture_output=True, text=True, timeout=60)

    def test_the_interpreter_really_is_empty(self, built):
        _zpath, out = built
        probe = subprocess.run([sys.executable, "-S", "-E", "-c", "import pk232py"], cwd=out,
                               capture_output=True, text=True)
        assert probe.returncode != 0 and "pk232py" in probe.stderr

    def test_the_selftest_runs_and_writes_its_results(self, built):
        _zpath, out = built
        r = self._run(out, "--selftest", "1991", "--call", "OE3GAS")
        assert r.returncode == 0, r.stderr[-800:]
        assert "Release      : 01.AUG.91" in r.stdout
        assert (out / "scan_results" / "scan_01.AUG.91_n1" / "banner.txt").exists()
        assert list((out / "scan_results").glob("results_OE3GAS_*.zip"))

    def test_the_plan_lists_the_commands_of_the_embedded_matrix(self, built):
        _zpath, out = built
        r = self._run(out, "--plan")
        assert r.returncode == 0 and "Would probe" in r.stdout and "ILFPACK" in r.stdout

    def test_there_is_no_update_matrix_in_the_kit(self, built):
        _zpath, out = built
        r = self._run(out, "--selftest", "1991", "--update-matrix")
        assert r.returncode == 2 and "kit" in r.stderr.lower()

    def test_all_asks_for_the_two_confirmations_before_anything(self, built):
        _zpath, out = built
        r = subprocess.run([sys.executable, "-S", "-E", "pk232_fw_scan.py", "--port", "COM99", "--all",
                            "--call", "OE3GAS"], cwd=out, input="no\n", capture_output=True, text=True, timeout=60)
        assert r.returncode == 5 and "radio" in r.stderr.lower()


class TestReadmeAndScripts:

    def test_the_german_readme_names_what_the_operator_must_know(self, built):
        _zpath, out = built
        text = (out / "README_DE.md").read_text(encoding="utf-8")
        for word in ("Funkgerät", "Dummy", "RESTART", "Pufferbatterie", "Autobaud", "--baud", "GitHub",
                     "Einverständnis", "Rufzeichen", "results_", "device_info"):
            assert word in text, word

    def test_the_english_readme_names_the_same(self, built):
        _zpath, out = built
        text = (out / "README_EN.md").read_text(encoding="utf-8")
        for word in ("radio", "dummy load", "RESTART", "battery", "autobaud", "--baud", "GitHub",
                     "consent", "callsign", "results_", "device_info"):
            assert word in text, word

    def test_both_readmes_say_the_default_run_is_the_safe_one(self, built):
        _zpath, out = built
        assert "--all" in (out / "README_DE.md").read_text(encoding="utf-8")
        assert "--all" in (out / "README_EN.md").read_text(encoding="utf-8")

    @pytest.mark.parametrize("name", ["run_scan.bat", "run_scan.sh"])
    def test_the_scripts_ask_port_baud_and_callsign_and_start_the_safe_run(self, built, name):
        _zpath, out = built
        text = (out / name).read_text(encoding="utf-8")
        for flag in ("--port", "--baud", "--call", "pk232_fw_scan.py"):
            assert flag in text
        assert "--all" not in text and "--update-matrix" not in text

    def test_the_form_has_the_fields_of_the_spec(self, built):
        _zpath, out = built
        text = (out / "device_info.txt").read_text(encoding="utf-8")
        for key in ("Model:", "EPROM label:", "Board options:", "Battery backup:", "Remarks:"):
            assert key in text
