# pk232py - Modern multimode terminal for AEA PK-232 / PK-232MBX TNC
# Copyright (C) 2026  OE3GAS  -  GPL v2
"""P90: build the scan kit for other radio amateurs.

    python tools/build_scan_kit.py [--out dist] [--date YYYY-MM-DD]

writes dist/pk232_scan_kit_<date>.zip with a STAND-ALONE scanner: tools/pk232_fw_scan.py with the few parts it
needs from PK232PY copied in at BUILD time (the wake-up byte and banner markers of the detection chain,
escape_converse(), verbose_line(), the command matrix reader) and the command matrix itself as an embedded
table. The generated file needs only the standard library and pyserial.

NOT part of the shipped application. Lernmodus: the scanner is the one source of truth - nothing in the kit
is typed twice; the builder cuts the import block out of the tool (between the "pk232py imports" markers)
and puts generated code in its place, so a change in tools/pk232_fw_scan.py or in PK232PY reaches the kit with
the next build. The zip is reproducible: the same sources and --date give the same bytes (fixed time stamps,
sorted entries).
"""

from __future__ import annotations

import argparse
import datetime as _dt
import inspect
import re
import sys
import zipfile
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "src"))

from pk232py.comm import command_matrix, constants, devices, pk232_hostmode_sub, serial_manager  # noqa: E402

SCANNER = REPO / "tools" / "pk232_fw_scan.py"
MATRIX_CSV = REPO / "src" / "pk232py" / "data" / "command_matrix.csv"
BEGIN = "# >>> pk232py imports"
END = "# <<< pk232py imports"
GENERATED = "# generated by build_scan_kit, do not edit - change tools/pk232_fw_scan.py or PK232PY and build again"

DEVICE_INFO_NOTE = "(the scanner fills in release, callsign, date and serial for every device it scans)"

# ---------------------------------------------------------------------------- texts of the kit

README_EN = """\
# PK-232 scan kit

This kit asks a PK-232 which commands its firmware knows, so that the command / firmware matrix of the
PK232PY project (github.com/oe3gas/PK232py) can grow by one more firmware release per device you scan.
Thank you for helping!

## Before you start - please read

* **Disconnect the radio from the TNC, or use a dummy load.** The default run only asks parameters, but a
  scanner must never be able to key a transmitter by accident.
* The default run is the **safe run**: it only reads parameters (and, on request, the harmless immediate
  commands). It does **not** set `MYCALL`, does not send `RESET` or `REINIT`, and does not transmit.
* It needs `EXPERT ON` for a moment, switches through the operating modes (Packet, Baudot, AMTOR, Morse, FAX,
  NAVTEX, Signal) to ask the commands that belong to them, and uses **`RESTART`** to read the power-on banner.
  `RESTART` is not destructive (your stored settings stay) but it **drops any connection** the TNC holds -
  run the scan with no link up.
* **The device is left as it was found:** before the scan the tool reads the operating mode, `EXPERT` and
  `ECHO` and the whole `DISPLAY` output (`settings_before.txt`); afterwards it restores them and reads
  `DISPLAY` again (`settings_after.txt`). Any difference is reported clearly at the end and in
  `settings_diff.txt`. A TNC with a RAM battery keeps its own settings (even `ECHO OFF`): the scan
  switches `ECHO ON` for its duration and back.
* `--all` (optional, **not** in the scripts) also sends the commands that switch modes, key the transmitter
  or may break the session (`TRANS`, `CALIBRATE`, `XMIT` ...) and records what they do. Only with no radio
  connected and you at the TNC; the tool asks twice and may ask you to power-cycle the TNC.

## What to do

1. Install Python 3.9 or newer and `pip install -r requirements.txt` (only `pyserial`).
2. Connect the TNC (serial port, normally 9600 baud) and switch it on. **Autobaud:** a TNC measures the baud
   rate from the first character after power-on - the tool sends a lone `*` first (autobaud). If your TNC does not
   answer, power-cycle it and run the scan again before sending anything else; a TNC with a battery may have
   other interface settings (another baud rate, 7 bits ...): try `--baud 1200` / `2400` / `4800` / `19200`.
3. Run `run_scan.bat` (Windows) or `./run_scan.sh` (Linux/macOS): it asks for the port, the baud rate and your
   callsign. Or by hand: `python pk232_fw_scan.py --port COM3 --baud 9600 --call YOURCALL`.
4. Repeat for every TNC. Each device gets its own folder in `scan_results/`.
5. Fill in `device_info.txt` in each folder (model, EPROM label, board options, battery yes/no, remarks).
6. Send back `scan_results/results_<callsign>_<date>.zip`.

## What comes back (per device)

`scan_<release>_<serial or n#>/` with `banner.txt` (the power-on banner, verbatim), `scan.csv` (one row per
command), `debug.log` (the raw dialogue), `settings_before.txt` / `settings_after.txt` (`DISPLAY`) and
`device_info.txt`; the zip holds all folders.

## Your consent

The results flow into the **public GitHub repository** of PK232PY (the command matrix and the raw files), with
**your callsign named as the source**. **Please confirm that you agree** (a reply to the e-mail is enough)
before the files are committed. If something looks wrong, power-cycle the TNC; nothing in the scan writes to
its memory except the temporary `EXPERT` / `ECHO` / operating mode, which are put back.
"""

README_DE = """\
# PK-232 Scan-Kit

Dieses Kit fragt einen PK-232, welche Befehle seine Firmware kennt, damit die Befehls-/Firmware-Matrix des
Projekts PK232PY (github.com/oe3gas/PK232py) mit jedem Gerät um einen Firmwarestand wächst. Danke fürs Mitmachen!

## Bitte vorher lesen

* **Funkgerät vom TNC abklemmen oder Dummy-Load anschließen.** Der Standardlauf fragt nur Parameter ab - ein
  Scanner darf aber nie versehentlich einen Sender tasten können.
* Der Standardlauf ist der **sichere Lauf**: er liest nur Parameter (auf Wunsch die harmlosen Sofortbefehle).
  Er setzt **kein** `MYCALL`, sendet kein `RESET` oder `REINIT` und sendet nichts aus.
* Er braucht kurz `EXPERT ON`, schaltet durch die Betriebsarten (Packet, Baudot, AMTOR, Morse, FAX, NAVTEX,
  Signal), um deren Befehle zu fragen, und benutzt **`RESTART`**, um das Einschaltbanner zu lesen. `RESTART`
  ist nicht zerstörend (die gespeicherten Einstellungen bleiben), **trennt aber jede bestehende Verbindung**
  des TNC - bitte ohne aufgebaute Verbindung scannen.
* **Das Gerät bleibt, wie es war:** vor dem Scan liest das Werkzeug Betriebsart, `EXPERT`, `ECHO` und die
  ganze Ausgabe von `DISPLAY` (`settings_before.txt`); danach stellt es alles wieder her und liest `DISPLAY`
  noch einmal (`settings_after.txt`). Jede Abweichung wird am Ende deutlich gemeldet und steht in
  `settings_diff.txt`. Ein TNC mit **Pufferbatterie** behält eigene Einstellungen (auch `ECHO OFF`): der Scan
  schaltet `ECHO ON` für seine Dauer ein und danach wieder aus.
* `--all` (optional, **nicht** in den Skripten) sendet auch die Befehle, die Betriebsarten wechseln, den
  Sender tasten oder die Sitzung brechen können (`TRANS`, `CALIBRATE`, `XMIT` ...), und hält fest, was sie
  bewirken. Nur ohne angeschlossenes Funkgerät und mit Ihnen am TNC; das Werkzeug fragt zweimal nach und
  bittet gegebenenfalls um ein Aus- und Einschalten.

## So geht es

1. Python 3.9 oder neuer installieren und `pip install -r requirements.txt` (nur `pyserial`).
2. TNC an die serielle Schnittstelle (üblich 9600 Baud) anschließen und einschalten. **Autobaud:** der TNC misst
   die Baudrate am ersten Zeichen nach dem Einschalten - das Werkzeug sendet zuerst ein einzelnes `*`. Antwortet
   Ihr TNC nicht, aus- und wieder einschalten und den Scan neu starten, bevor etwas anderes gesendet wird; ein TNC
   mit Pufferbatterie kann andere Schnittstellenwerte haben (andere Baudrate, 7 Bit ...): `--baud 1200` / `2400` /
   `4800` / `19200` probieren.
3. `run_scan.bat` (Windows) oder `./run_scan.sh` (Linux/macOS) starten: es fragt Port, Baudrate und Ihr Rufzeichen.
   Oder von Hand: `python pk232_fw_scan.py --port COM3 --baud 9600 --call IHRRUFZEICHEN`.
4. Für jeden TNC wiederholen. Jedes Gerät bekommt einen eigenen Ordner in `scan_results/`.
5. In jedem Ordner `device_info.txt` ausfüllen (Modell, EPROM-Beschriftung, Platinenoptionen, Pufferbatterie ja/nein,
   Bemerkungen).
6. `scan_results/results_<rufzeichen>_<datum>.zip` zurückschicken.

## Was je Gerät zurückkommt

`scan_<release>_<seriennr oder n#>/` mit `banner.txt` (das Einschaltbanner, wörtlich), `scan.csv` (eine Zeile je
Befehl), `debug.log` (der rohe Dialog), `settings_before.txt` / `settings_after.txt` (`DISPLAY`) und
`device_info.txt`; das ZIP enthält alle Ordner.

## Ihr Einverständnis

Die Ergebnisse fließen in das **öffentliche GitHub-Repository** von PK232PY ein (Befehlsmatrix und Rohdateien), mit
**Ihrem Rufzeichen als Quelle**. **Bitte bestätigen Sie, dass Sie einverstanden sind** (eine Antwort per E-Mail genügt),
bevor die Dateien committet werden. Wirkt etwas falsch, den TNC aus- und einschalten; der Scan schreibt nichts in seinen
Speicher außer dem vorübergehenden `EXPERT` / `ECHO` / der Betriebsart, die zurückgesetzt werden.
"""

RUN_BAT = """\
@echo off
rem PK-232 scan kit - the SAFE run (parameters only). Disconnect the radio from the TNC first.
set /p PORT=Serial port (e.g. COM3):
set /p BAUD=Baud rate [9600]:
if "%BAUD%"=="" set BAUD=9600
set /p CALL=Your callsign:
python pk232_fw_scan.py --port %PORT% --baud %BAUD% --call %CALL%
pause
"""

RUN_SH = """\
#!/bin/sh
# PK-232 scan kit - the SAFE run (parameters only). Disconnect the radio from the TNC first.
printf 'Serial port (e.g. /dev/ttyUSB0): '; read PORT
printf 'Baud rate [9600]: '; read BAUD
[ -z "$BAUD" ] && BAUD=9600
printf 'Your callsign: '; read CALL
python3 pk232_fw_scan.py --port "$PORT" --baud "$BAUD" --call "$CALL"
"""


# ---------------------------------------------------------------------------- the standalone scanner

def _literal_lines(name: str, text: str) -> str:
    """A text as a Python expression ``name = ( 'line\\n' ... )``, one literal per line."""
    parts = text.splitlines(keepends=True)
    return f"{name} = (\n" + "".join(f"    {part!r}\n" for part in parts) + ")\n"


def generated_block() -> str:
    """What replaces the pk232py import block: copies of what the scanner uses, made NOW from the live code."""
    devs = tuple((d.label, d.release) for d in devices.KNOWN_DEVICES)
    matrix_csv = MATRIX_CSV.read_text(encoding="utf-8").replace("\r\n", "\n")
    cm_source = Path(command_matrix.__file__).read_text(encoding="utf-8").replace("\r\n", "\n")
    return "\n".join([
        "# ---- generated at build time: what the scanner needs from PK232PY (no pk232py is imported) ----",
        "import types",
        "from typing import Callable",
        "",
        f"VERBOSE_EOL = {constants.VERBOSE_EOL!r}",
        inspect.getsource(constants.verbose_line).rstrip("\n"),
        "",
        f"FRAME_HOST_OFF = {constants.FRAME_HOST_OFF!r}",
        f"FACTORY_BANNER_LINES = {constants.FACTORY_BANNER_LINES!r}",
        inspect.getsource(constants.is_factory_banner).rstrip("\n"),
        "",
        f"_WAKEUP = {serial_manager._WAKEUP!r}",
        f"_BANNER_MARKERS = {serial_manager._BANNER_MARKERS!r}",
        f"_XON_BYTE = {serial_manager._XON_BYTE!r}",
        f"_ESCAPE_CONVERSE_TIMEOUT = {pk232_hostmode_sub._ESCAPE_CONVERSE_TIMEOUT!r}",
        "",
        inspect.getsource(pk232_hostmode_sub.escape_converse).rstrip("\n"),
        "",
        "# the devices known to the project (label, release) - only to name the device in the report",
        f"KNOWN_DEVICES = tuple(types.SimpleNamespace(label=l, release=r) for l, r in {devs!r})",
        "",
        "# the command matrix: its reader (a copy of comm/command_matrix.py) and the matrix as a table",
        _literal_lines("_MATRIX_CSV", matrix_csv),
        _literal_lines("_CM_SOURCE", cm_source),
        "cm = types.ModuleType('command_matrix')",
        "cm.__file__ = 'command_matrix.py (embedded)'   # the copy computes DATA_FILE from it (never read)",
        "sys.modules['command_matrix'] = cm            # dataclasses look the module up by name",
        "exec(compile(_CM_SOURCE, 'command_matrix.py (embedded)', 'exec'), cm.__dict__)",
        "cm.load = lambda path=None: cm.parse(_MATRIX_CSV)      # no data file here: the embedded table",
        "cm._adopt([c[3:] for c in _MATRIX_CSV.split('\\n', 1)[0].split(',') if c.startswith('fw_')])",
        "cm.reload()",
        "# ---- end of the generated block ----",
    ]) + "\n"


def build_standalone_source() -> str:
    """The text of the stand-alone scanner."""
    src = SCANNER.read_text(encoding="utf-8").replace("\r\n", "\n")
    begin, end = src.index(BEGIN), src.index(END)
    src = src[:begin] + generated_block() + src[end + len(END) + 1:]
    assert src.count("\n_KIT = False\n") == 1
    src = src.replace("\n_KIT = False\n", "\n_KIT = True\n")
    head, rest = src.split("\n", 2)[:2], src.split("\n", 2)[2]       # shebang and coding line stay first
    return "\n".join(head + [GENERATED, rest])


def embedded_matrix_text(source: str) -> str:
    """Python text that defines only ``_MATRIX_CSV`` - cut out of a generated scanner (for the tests)."""
    start = source.index("_MATRIX_CSV = (")
    end = source.index("_CM_SOURCE = (")
    return source[start:end]


# ---------------------------------------------------------------------------- the zip

def _device_info_form() -> str:
    text = Path(SCANNER).read_text(encoding="utf-8")
    m = re.search(r'DEVICE_INFO_TEMPLATE = """(.*?)"""', text, re.S)
    template = m.group(1)
    template = template.split("# Filled in by the scanner:")[0]
    return template + f"# {DEVICE_INFO_NOTE}\n"


def kit_files() -> dict:
    """{name in the zip: (bytes, unix mode)}"""
    return {
        "pk232_fw_scan.py": (build_standalone_source().encode("utf-8"), 0o644),
        "requirements.txt": (b"pyserial\n", 0o644),
        "README_DE.md": (README_DE.encode("utf-8"), 0o644),
        "README_EN.md": (README_EN.encode("utf-8"), 0o644),
        "run_scan.bat": (RUN_BAT.replace("\n", "\r\n").encode("utf-8"), 0o644),
        "run_scan.sh": (RUN_SH.encode("utf-8"), 0o755),
        "device_info.txt": (_device_info_form().encode("utf-8"), 0o644),
    }


def build_kit(out_dir, date: str = "") -> Path:
    """dist/pk232_scan_kit_<date>.zip - reproducible for the same sources and date."""
    date = date or _dt.date.today().isoformat()
    y, mo, d = (int(x) for x in date.split("-"))
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    zpath = out_dir / f"pk232_scan_kit_{date}.zip"
    with zipfile.ZipFile(zpath, "w", zipfile.ZIP_DEFLATED) as z:
        for name, (data, mode) in sorted(kit_files().items()):
            info = zipfile.ZipInfo(name, date_time=(y, mo, d, 0, 0, 0))
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = (mode & 0xFFFF) << 16
            z.writestr(info, data)
    return zpath


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description="Build the PK-232 scan kit for external operators")
    ap.add_argument("--out", default=str(REPO / "dist"), help="output directory (default dist/)")
    ap.add_argument("--date", default="", help="date in the file name and the zip (default today)")
    args = ap.parse_args(argv)
    print(f"[+] {build_kit(args.out, args.date)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
