# pk232py - Modern multimode terminal for AEA PK-232 / PK-232MBX TNC
# Copyright (C) 2026  OE3GAS  -  GPL v2
"""P80: scan the application for every Host Mode mnemonic it sends, and write
docs/MNEMONIC_AUDIT.md from comm/mnemonic_registry.py.

    python tools/gen_mnemonic_audit.py            # check: exit 1 if the file is stale
    python tools/gen_mnemonic_audit.py --update   # rewrite docs/MNEMONIC_AUDIT.md

NOT part of the shipped application. tests/test_mnemonic_registry.py imports
scan_sources() and render_audit() from here, so the test and the generated
file can never disagree about what "a mnemonic the app sends" is.

Lernmodus: the scan reads the SOURCE with ``ast`` (not with a regex), so
mnemonics in comments and docstrings are ignored and only real call arguments
count. A mnemonic is "sent" when it is a bytes literal of length 2 in one of:
  * the first argument of build_command() / send_command(),
  * the second argument of build_ch_cmd() / build_ch_command() /
    send_channel_command() (the first is the channel number),
  * a value of ``_CLEAR_TX_STOP_CMD`` or the second item of a tuple in
    ``toggle_map`` (main_window.py - the mnemonic reaches build_command()
    through a variable there),
  * a row of comm/host_params.py (sent by ParamApplier through send_command()).
"""

from __future__ import annotations

import ast
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SRC = REPO / "src"
PKG = SRC / "pk232py"
AUDIT_FILE = REPO / "docs" / "MNEMONIC_AUDIT.md"

_FIRST_ARG = {"build_command", "send_command"}
_SECOND_ARG = {"build_ch_cmd", "build_ch_command", "send_channel_command"}
_TABLE_NAMES = {"_CLEAR_TX_STOP_CMD", "toggle_map"}

# (file relative to src/pk232py, line, how it is reached)
Site = tuple


def _is_mnemonic(node: ast.AST) -> bool:
    return (isinstance(node, ast.Constant) and isinstance(node.value, bytes)
            and len(node.value) == 2)


def _call_name(node: ast.Call) -> str:
    f = node.func
    return f.id if isinstance(f, ast.Name) else getattr(f, "attr", "")


def scan_sources(pkg: Path = PKG) -> dict:
    """{mnemonic bytes: [(relative file, line, call name), ...]} for every
    mnemonic the application (without tests/) sends. Sorted by mnemonic."""
    found: dict = {}

    def add(mn: bytes, rel: str, line: int, how: str) -> None:
        found.setdefault(mn, []).append((rel, line, how))

    for path in sorted(pkg.rglob("*.py")):
        rel = path.relative_to(pkg).parts
        if rel[0] == "tests":
            continue
        rel_path = path.relative_to(pkg).as_posix()
        tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
        for node in ast.walk(tree):
            if isinstance(node, ast.Call):
                name = _call_name(node)
                if name in _FIRST_ARG and node.args and _is_mnemonic(node.args[0]):
                    add(node.args[0].value, rel_path, node.lineno, name)
                elif name in _SECOND_ARG and len(node.args) > 1 and _is_mnemonic(node.args[1]):
                    add(node.args[1].value, rel_path, node.lineno, name)
            elif isinstance(node, (ast.Assign, ast.AnnAssign)):
                targets = node.targets if isinstance(node, ast.Assign) else [node.target]
                names = {t.id for t in targets if isinstance(t, ast.Name)}
                if not names & _TABLE_NAMES or node.value is None:
                    continue
                for sub in ast.walk(node.value):
                    if _is_mnemonic(sub):
                        add(sub.value, rel_path, sub.lineno, sorted(names)[0])

    # host_params.py: the parameter table (sent by ParamApplier).
    sys.path.insert(0, str(SRC))      # the real host_params, also when *pkg* is a test copy
    try:
        from pk232py.comm.host_params import HOST_PARAMS
    finally:
        sys.path.pop(0)
    for row in HOST_PARAMS:
        if row.mnemonic:
            add(row.mnemonic, "comm/host_params.py", 0, f"HostParam {row.name}")
    return dict(sorted(found.items()))


def render_audit() -> str:
    """The text of docs/MNEMONIC_AUDIT.md, from the registry."""
    sys.path.insert(0, str(SRC))
    try:
        from pk232py.comm.mnemonic_registry import REGISTRY, RELEASES
    finally:
        sys.path.pop(0)
    lines = [
        "<!-- generated by test_mnemonic_registry / tools/gen_mnemonic_audit.py, do not edit -->",
        "# Host Mode mnemonic audit (P80)",
        "",
        "Generated from `src/pk232py/comm/mnemonic_registry.py`. A cell shows the",
        "evidence for that release (`-` = none). `TX` = keys the transmitter.",
        "",
        "| Mnemonic | Meaning | Kind | TX | " + " | ".join(RELEASES) + " |",
        "|---|---|---|---|" + "---|" * len(RELEASES),
    ]
    for entry in sorted(REGISTRY.values(), key=lambda e: e.mnemonic):
        cells = [entry.evidence.get(rel, "-") for rel in RELEASES]
        lines.append(
            f"| `{entry.mnemonic.decode('ascii')}` | {entry.meaning} | {entry.kind} | "
            f"{'TX' if entry.transmits else ''} | " + " | ".join(c.replace('|', '/') for c in cells) + " |")
    lines.append("")
    return "\n".join(lines)


def main(argv: list) -> int:
    text = render_audit()
    if "--update" in argv:
        AUDIT_FILE.write_text(text, encoding="utf-8", newline="\n")
        print(f"written: {AUDIT_FILE}")
        return 0
    current = AUDIT_FILE.read_text(encoding="utf-8") if AUDIT_FILE.exists() else ""
    if current.replace("\r\n", "\n") != text:
        print("docs/MNEMONIC_AUDIT.md is stale - run: "
              "python tools/gen_mnemonic_audit.py --update")
        return 1
    print("docs/MNEMONIC_AUDIT.md is current")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
